### PR TITLE
Added assets for simulate

### PR DESCRIPTION
**Pull request by Vaibhav-Chopra-GT**
Added all the assets in `web-assets` directory as discussed in https://github.com/builtree/simulate/issues/201

@yashlamba please let me know if any changes are required!

### CODE REVIEW

**Comment by yashlamba** [comment]
@yashugarg can you review this? Why are some images of different sizes, is this in the app as well?

**Comment by yashugarg** [comment]
@Vaibhav-Chopra-GT It looks like the assets are not all of the same dimensions.
We generally keep images 300x300, so resize the images for Rose Pattern, Fourier series, and Toothpick pattern.
Its just 3 steps:
1. Change the background of the simulation
2. Take a screenshot
3. Resize it to 300x300
PS: You need to take screenshots individually for light and dark mode, and try to keep similar values for the curve in both screenshots!

**Review by yashugarg — CHANGES_REQUESTED** [review]
I see that you've changed the dimensions, but it turns out you missed step 1.
The default canvas color is grey and you need to change it to solid white and black before taking the screenshot.
Please refer to other images for reference!

**Review by yashugarg — APPROVED** [review]
Looks good to me!
@yashlamba, please review and merge the PR

**Review by yashlamba — APPROVED** [review]

**Comment by yashlamba** [comment]
@Vaibhav-Chopra-GT @yashugarg Sorry for the late review, got caught up in things, this looks good, let's try using these first in a PR, then work on https://github.com/builtree/simulate/issues/201

**Pull request merged**
